theme: minima
title: Dynamic Contract Protocol (DCP)
description: Contract-first, dynamic API protocol for AI-powered apps
author: gokayokutucu
url: "https://gokayokutucu.github.io"
baseurl: "/dcp-spec"
repository: "https://github.com/gokayokutucu/dcp-spec"
plugins:
  - jekyll-sitemap